### ISSUE TITLE
Using composer update

### ISSUE THREAD

**Issue by LostKobrakai** [harikt/pwmoduleinstaller#1]
Doing a `composer update [module]` does result in this message even though it's been installed via composer in the first place.

> Package "lostkobrakai/migrations:dev-master" listed for update is not installed. Ignoring.

**Comment by LostKobrakai** [comment]
ah shit the :dev-master was the issue, sorry for bothering.

**Comment by harikt** [comment]
@LostKobrakai no problem. Just found the issue you reported. 

Happy to know it has been resolved.

Thank you
