### ISSUE TITLE
Issues with Composer 2

### ISSUE THREAD

**Issue by tiefenb** [harikt/pwmoduleinstaller#2]
Since Composer 2, there are some issues with this:
see more in comments here: https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb

**Comment by timohausmann** [comment]
```
  - Installing hari/pw-module (1.0.0): Extracting archive
Loading "hari/pw-module" which is a legacy composer-installer built for Composer 1.x, it is likely to cause issues as you are running Composer 2.x.
```

A site/modules folder is created but it's empty after running `composer require wanze/template-engine-factory:^2.0`.
